name: test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make build
      - run: make test
